"""Initial migration

Revision ID: 2ae499012a20
Revises: 720136f4345e
Create Date: 2025-11-03 18:13:22.298583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ae499012a20'
down_revision: Union[str, Sequence[str], None] = '720136f4345e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('education_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('academic_performance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('certifications', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('problem_solving_approach', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('environment_preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('learning_style', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interests', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extracurricular_activities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('behavioral_traits', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('predicted_career', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('career_rationale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('growth_roadmap', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skill_gap_analysis', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommendations', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alternative_career', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prediction_pkey'))
    )
    # ### end Alembic commands ###
